---
- name: RHEL server golden AMI preparations
  hosts: 'all'
  become: yes
  become_method: sudo
  environment:
    LANG: en_US.UTF-8
    LC_ALL: en_US.UTF-8
  vars_files:
    - /tmp/rhel_config.yml

  tasks:
  - name: remove rhui repos
    yum:
      name: *rhui*
      state: removed
    tags:
      - pre_task

  - name: configure product-id.conf
    copy:
      dest: /etc/yum/pluginconf.d/product-id.conf
      content: |
        [main]
        enabled=1
    tags:
      - pre_task

  - name: subscription manager
    redhat_subscription:
      state: present
      activationkey: "{{ rhel_activation_key }}"
      org_id: "{{ org_id }}"
      auto_attach: true
    tags:
      - pre_task

  - name: enable repos
    rhsm_repository:
      name:
        - rhel-8-for-aarch64-appstream-rpms
        - rhel-8-for-aarch64-baseos-rpms
        - ansible-2.9-for-rhel-8-aarch64-rpms
      state: enabled
      purge: yes
    tags:
      - pre_task

  - name: Update all packages
    yum:
      name: "*"
      state: latest

  - name: install chrony
    include_role:
      name: oasis_roles.system.chrony
    tags:
      - software

  - name: motd
    copy:
      dest: /etc/motd
      content: |
        #######################
        ## Hic sunt dracones ##
        #######################
    tags:
     - post_software

  - name: unregister
    redhat_subscription:
      state: absent

  - name: remove any persistent udev rules
    file:
      path: /etc/udev/rules.d/70-persistent-net.rules
      state: absent
 
  - name: remove HWADDR MAC line from ifcfg-eth0
    lineinfile:
      path: /etc/sysconfig/network-scripts/ifcfg-eth0
      state: absent
      regexp: '^HWADDR'  

  - name: build ssh_host_ file list from wildcard
    find:
      paths: /etc/ssh
      patterns: "^ssh_host_"
      use_regex: true
    register: ssh_host_files_to_delete

  - name: remove ssh_host_ files
    file:
      path: "{{ item.path }}"
      state: absent
    with_items: "{{ ssh_host_files_to_delete.files }}"
